version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - 3305:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: 'redis:latest'
    ports:
      - 6378:6379
